version: '3'
networks:
  cluster_piccoling_default:
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: piccoling
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  usuarios:
    image: isabellaperezc/usuariopiccoling
    depends_on: 
      - db
    ports:
      - "3001:3001"

  inventario:
    image: isabellaperezc/inventariopiccoling
    depends_on: 
      - db
    ports:
      - "3002:3002"

  facturas:
    image: isabellaperezc/facturaspiccoling
    depends_on:
      - db
    ports:
      - "3003:3003"

  web:
    image: isabellaperezc/webpiccoling
    depends_on:
      - usuarios
      - inventario
      - facturas
    ports:
      - "2080:80"

  